config/routes.rb
RaveApp::Application.routes.draw do

  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]

  root :to => "pages#home"

  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'    
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/signup',  :to => 'users#new'
  
  

  

end

app/views/pages/about.html.erb
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/help.html.erb
<p>Find me in app/views/pages/help.html.erb</p>

app/views/pages/home.html.erb
<% if signed_in? %>
  <table class="front" summary="For signed-in users">
    <tr>
      <td class="main">
        <h1 class="micropost">What's up?</h1>
        <%= render 'shared/micropost_form' %>
        <%= render 'shared/feed' %>
      </td>
      <td class="sidebar round">
        <%= render 'shared/user_info' %>
        <%= render 'shared/stats' %>
      </td>
    </tr>
  </table>
<% else %>
  <h1>Sample App</h1>

  <p>
    This is the home page for the Rave App! A twisted version of the 
    <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a> sample app!
  </p>

  <%= link_to "Sign up now!", signup_path, :class => "signup_button round" %>
<% end %>